import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {readJourneys,SAVED_KEY,validJourneys} from './journeys.js';
import './accounts.css';
const Context=createContext(null),defaults={inbound:true,gate:true,boarding:true,delay:true,probability:true,landing:false,baggage:false};
export const cleanPreferences=value=>Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,typeof value?.[k]==='boolean'?value[k]:v]));
export const useAccount=()=>useContext(Context);
export function AccountProvider({children}){
 const [client,setClient]=useState(null),[user,setUser]=useState(null),[ready,setReady]=useState(false),[saved,setSaved]=useState([]),[open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const currentUser=useRef(null);
 const [emailReady,setEmailReady]=useState(false);
 useEffect(()=>{let active=true,subscription;fetch(`${import.meta.env.BASE_URL}api/accounts/config`,{signal:AbortSignal.timeout(10000)}).then(r=>r.ok?r.json():null).then(async config=>{
  if(!config?.enabled)return;
  const {createClient}=await import('@supabase/supabase-js');if(!active)return;
  const c=createClient(config.url,config.publishableKey,{auth:{flowType:'pkce'}});setClient(c);setEmailReady(config.emailReady===true);
  subscription=c.auth.onAuthStateChange((_event,session)=>{if(active){currentUser.current=session?.user?.id||null;setUser(session?.user||null);setSaved([]);}}).data.subscription;
 }).catch(()=>{}).finally(()=>{if(active)setReady(true);});return()=>{active=false;subscription?.unsubscribe();};},[]);
 useEffect(()=>{if(!client||!user)return;let active=true;setBusy(true);client.from('saved_flights').select('journey').eq('user_id',user.id).order('created_at',{ascending:false}).then(({data,error})=>{if(!active)return;if(error)setError('Your saved flights could not load. Please try again.');else setSaved(validJourneys(data.map(r=>r.journey)));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[client,user]);
 async function save(item){if(!user){setOpen(true);return false;}setBusy(true);setError('');const uid=user.id;
  try{const {error}=await client.from('saved_flights').upsert({user_id:uid,flight_key:item.key,journey:item});if(error)throw error;if(currentUser.current===uid)setSaved(old=>[item,...old.filter(x=>x.key!==item.key)]);return true;}catch{setError('This flight was not saved. Check your connection and try again.');return false;}finally{setBusy(false);}}
 async function remove(key){if(!user)return;setBusy(true);const uid=user.id,item=saved.find(x=>x.key===key);if(item){const {error}=await client.from('notification_preferences').delete().eq('user_id',uid).eq('flight_key',`${item.ident}.${item.date}`);if(error){setError('We could not stop this flight’s updates. Please try again.');setBusy(false);return;}}const {error}=await client.from('saved_flights').delete().eq('user_id',uid).eq('flight_key',key);if(error)setError('We could not remove that flight. Please try again.');else if(currentUser.current===uid)setSaved(old=>old.filter(x=>x.key!==key));setBusy(false);}
 const value={client,user,ready,saved,busy,error,save,remove,emailReady,open:()=>setOpen(true)};
 return <Context.Provider value={value}>{children}{error&&<div className="account-notice" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss account message">×</button></div>}{open&&<AccountDialog account={value} close={()=>setOpen(false)}/>}</Context.Provider>;
}
export function AccountButton(){const a=useAccount();return a?.client?<button className="nav-link account-entry" onClick={a.open}>{a.user?'Account':'Sign in'}</button>:null;}
function AccountDialog({account:a,close}){
 const [email,setEmail]=useState(''),[token,setToken]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),box=useRef(null);
 useEffect(()=>{const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';box.current.querySelector('button').focus();const key=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=[...box.current.querySelectorAll('button,input')].filter(x=>!x.disabled&&x.getClientRects().length),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};addEventListener('keydown',key);return()=>{removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus();};},[]);
 async function submit(e){e.preventDefault();setBusy(true);setMessage('');try{const {error}=sent?await a.client.auth.verifyOtp({email,token,type:'email'}):await a.client.auth.signInWithOtp({email});if(error)throw error;if(sent)close();else{setSent(true);setMessage('Check your email for a sign-in code. It may take a minute.');}}catch{setMessage(sent?'That code could not be verified. Check it or request another code.':'We could not send a code. Please wait a minute and try again.');}finally{setBusy(false);}}
 return <div className="account-overlay"><section ref={box} className="account-dialog" role="dialog" aria-modal="true" aria-labelledby="account-title"><button className="account-close" onClick={close} aria-label="Close account">×</button><h2 id="account-title">{a.user?'Your account':'Keep your flights together'}</h2>{a.user?<><p>{a.user.email}</p><p>Saved flights and notification preferences stay with your account. Email and text delivery are not activated by signing in.</p><button disabled={a.busy||busy} onClick={async()=>{setBusy(true);let ok=true;for(const item of readJourneys(SAVED_KEY))if(!await a.save(item))ok=false;setMessage(ok?'Flights from this browser copied to your account.':'Some flights could not be copied. Try again.');setBusy(false);}}>Import flights saved on this browser</button><button onClick={async()=>{setBusy(true);const {error}=await a.client.auth.signOut();setBusy(false);if(error)setMessage('Sign-out failed. Please try again.');else close();}} disabled={busy}>Sign out</button></>:<form onSubmit={submit}><p>Sign in with an email code to save flights across devices. No password needed.</p><label>Email<input type="email" required autoComplete="email" value={email} disabled={sent} onChange={e=>setEmail(e.target.value)}/></label>{sent&&<label>Sign-in code<input required inputMode="numeric" autoComplete="one-time-code" value={token} onChange={e=>setToken(e.target.value.trim())}/></label>}<button disabled={busy}>{busy?'Please wait…':sent?'Verify and sign in':'Email me a code'}</button>{sent&&<button type="button" disabled={busy} onClick={()=>{setSent(false);setToken('');}}>Use another email or request a new code</button>}</form>}{message&&<p role="status">{message}</p>}</section></div>;
}
