import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import AppRecovery from './AppRecovery.jsx';
import './product-polish.css';
import './styles.css';
import './premium.css';
import './index.css';
import './app.css';
import './trend-fix.css';
import './readable-index.css';
import './glass.css';
import './bar2.css';
import './natural-search.css';
import './bar-tooltip.css';
import './audit2.css';
import './chart-polish.css';
import './readable-fix.css';
import './stunning.css';
import './traveler.css';
createRoot(document.getElementById('root')).render(<AppRecovery><App/></AppRecovery>);
