import React from 'react';
const when=value=>value?new Date(value).toLocaleString():'Time not reported';
export default function RiskContext({index,cached}){
 if(!index)return null;
 const audit=index.audit,trend=index.historical_trend;
 return <section className="risk-context" aria-label="Understanding your delay estimate">
  {cached&&<p>Saved results: these source reports are not a fresh check. Refresh when service is available.</p>}
  {audit?.warning_summary&&<div className="risk-signal-note"><strong>{index.score>=65?'Elevated delay risk':index.score>=35?'Some signs of disruption':'Watch the reported conditions'}</strong><p>The percentage is an estimate, not a promise. Reported weather, airport restrictions or a late incoming plane can still affect your flight. Follow your airline’s boarding updates.</p></div>}
  {!!index.airport_indicators?.length&&<details><summary>Airport conditions</summary><p>Airport-wide reports, not confirmed causes for your flight. “Not reported” is not a guarantee.</p><div className="airport-signal-grid">{index.airport_indicators.map((airport,i)=><article key={i}><h4>{airport.airport}</h4>{airport.items.map(item=><div className="airport-signal" key={item.label}><span>{item.label}</span><strong className={cached?'unavailable':item.status}>{cached?'Saved report':item.status==='reported'?'Reported':item.status==='unavailable'?'Unavailable':'Not reported'}</strong>{item.detail&&<p>{item.detail}</p>}</div>)}<small>{airport.source} · {when(airport.updated_at)}</small></article>)}</div></details>}
  {trend&&<details><summary>How this flight usually performs</summary><p>{trend.scope}. Actual departures only; 15+ minutes late counts as delayed.</p>{trend.sufficient?<div className="route-history-bars">{[['Earlier departures',trend.earlier],['Recent departures',trend.recent]].map(([label,group])=><div key={label}><strong>{label}: {group.delayed_percent}% delayed</strong><div className="history-track"><span style={{width:`${group.delayed_percent}%`}}/></div><small>{group.samples} completed flights · {new Date(group.from).toLocaleDateString()}–{new Date(group.to).toLocaleDateString()}</small></div>)}</div>:<p>Not enough comparable completed flights to show a reliable change over time.</p>}<p>Airline-wide live operations are a separate snapshot, not a historical airline reliability trend.</p></details>}
  {index.airline_history&&<details><summary>Recent airline reliability</summary><p>{index.airline_history.scope}.</p>{index.airline_history.sufficient?<p>Earlier sample: {index.airline_history.earlier.delayed_percent}% left 15+ minutes late ({index.airline_history.earlier.samples} flights). Recent sample: {index.airline_history.recent.delayed_percent}% ({index.airline_history.recent.samples} flights).</p>:<p>Not enough completed departures were returned for an airline trend. We won’t substitute scheduled or estimated outcomes.</p>}</details>}
  {audit&&<details className="risk-audit"><summary>Why this estimate · sources and changes</summary><p>{audit.policy}</p><p>{index.movement?.explanation} Changes below include data availability, not just changes in conditions.</p><div className="risk-audit-grid">{audit.rows.map(row=><article key={row.key}><h4>{row.label}</h4><span className="evidence-label">{row.evidence_label}</span><p>{row.detail}</p><strong>{row.value===null?'Not included':`${row.contribution_points} points of the overall estimate`}</strong><p>{row.change_reason}{row.change_points!==null?` (${row.change_points>0?'+':''}${row.change_points} points)`:''}</p><details><summary>Source receipt</summary><p>{row.source}</p><pre>{JSON.stringify(row.source_detail,null,2)}</pre></details></article>)}</div></details>}
 </section>;
}
