import React,{useEffect,useState} from 'react';
export default function TakeoffSlot({slot,airport,cached,scheduled}){
 const [now,setNow]=useState(Date.now);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
 if(!slot||slot.status==='not_applicable')return null;
 if(['assigned','revised'].includes(slot.status)&&(!Number.isFinite(Date.parse(slot.verified_at))||now-Date.parse(slot.verified_at)>300000||Date.parse(slot.assigned_time)<now-900000))slot={status:'stale',reason:'This assignment needs a fresh check. Refresh the flight before relying on its takeoff slot.'};
 const assigned=!cached&&['assigned','revised'].includes(slot.status)&&slot.assigned_time;
 const noFaaAssignment=slot.provider==='FAA EDCT public lookup'&&/No date-matched assignment|does not exactly match/.test(slot.reason||'');
 const time=value=>{try{return new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:airport?.timezone||'UTC',timeZoneName:'short'});}catch{return 'Time unavailable';}};
 const zulu=value=>new Date(value).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZone:'UTC'})+' UTC (Zulu)';
 if(!assigned)return <details className="takeoff-slot takeoff-slot-summary"><summary>ATC / EDCT · {cached?'saved data':slot.status==='removed'?'removed':slot.status==='not_assigned'||noFaaAssignment?'none reported':'check unavailable'}</summary><p>{cached?'A current assignment cannot be confirmed from saved flight details.':slot.status==='removed'?'The source reports that the previous slot was removed. This does not mean the flight is cleared to take off.':slot.status==='not_assigned'?'The connected source explicitly reports no assignment. This is not an on-time guarantee.':noFaaAssignment?'The FAA lookup returned no matching EDCT assignment for this flight. An assignment can still be issued later.':slot.reason}</p><p>An estimated takeoff time is not an assigned ATC slot. Follow your airline’s boarding time.</p></details>;
 return <section className="takeoff-slot assigned" aria-label="Assigned ATC takeoff slot"><span className="traveler-kicker">{slot.authority} · Air traffic control</span><h3>Assigned takeoff time: {time(slot.assigned_time)}</h3><p>Not your boarding time. The slot can change.</p><details><summary>Verify time &amp; source</summary><p>Source time: {zulu(slot.assigned_time)}. The headline shows the departure airport’s local time.</p>{scheduled&&<p>Scheduled gate departure: {time(scheduled)}. Leaving the gate and taking off are different events.</p>}{slot.filed_departure&&<p>FAA filed departure: {zulu(slot.filed_departure)}.</p>}{slot.status==='revised'&&<p>Assignment updated{slot.previous_time?` from ${time(slot.previous_time)}`:''}.</p>}{slot.reason&&<p>{slot.reason}</p>}{slot.control_element&&<p>FAA control element: {slot.control_element}. The lookup does not specify the delay reason.</p>}<p>Not gate departure or takeoff clearance. Follow your airline’s boarding time.</p><p>{slot.notice}</p><small>Source: {slot.provider} · Verified {time(slot.verified_at)}</small>{slot.source_url==='https://www.fly.faa.gov/edct/'&&<p><a href={slot.source_url} target="_blank" rel="noopener noreferrer">Check the FAA EDCT lookup ↗</a></p>}</details></section>;
}
