import React,{useState,useEffect,useRef} from 'react';
import './trip-strategy.css';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
const defaults={priority:'simpler',avoidRedeye:false,avoidAirportChanges:true,avoidRegional:false,minLayover:75,readyMinutes:120};
const when=t=>t?new Date(t).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}):'Time unavailable';
const tone=s=>s===null?'unknown':s>=60?'high':s>0?'moderate':'quiet';

export function Preferences({value,onChange}){
  return <details className="trip-preferences"><summary>Your travel preferences</summary><p>Saved in this browser. These choices help us sort other flights for you. They do not change your booking.</p><div className="preference-grid"><label>Prioritize<select value={value.priority} onChange={e=>onChange({...value,priority:e.target.value})}><option value="simpler">Fewer changes of plane</option><option value="price">Lowest listed price</option><option value="earliest">Earliest arrival</option></select></label><label>Time between connecting flights · minutes<input type="number" min="30" max="360" value={value.minLayover} onChange={e=>onChange({...value,minLayover:e.target.value})}/></label><label>Time needed before a backup departs · minutes<input type="number" min="30" max="720" value={value.readyMinutes} onChange={e=>onChange({...value,readyMinutes:e.target.value})}/></label></div><div className="preference-checks">{[['avoidRedeye','Avoid overnight departures (10pm–6am local)'],['avoidAirportChanges','Avoid airport changes during connections'],['avoidRegional','Avoid regional jets where aircraft type is reported']].map(([key,label])=><label key={key}><input type="checkbox" checked={value[key]} onChange={e=>onChange({...value,[key]:e.target.checked})}/>{label}</label>)}</div><small>Overnight flying after an earlier departure is not screened. Missing aircraft types and cancellation patterns remain unverified. We never call “fewer connections” a proven minimum-risk choice.</small></details>;
}

function RiskTimeline({timeline,connection}){
  const [horizon,setHorizon]=useState(24),[selected,setSelected]=useState(0);
  const rows=timeline.rows.filter(r=>r.hours<=horizon),index=Math.min(selected,rows.length-1),r=rows[index];
  const x=i=>30+i*660/(rows.length-1),y=s=>160-s*1.3;
  return <article className="trip-timeline"><header><div><span className="traveler-kicker">What’s ahead</span><h4>Conditions along your trip</h4></div><div className="horizon-picker" aria-label="Timeline horizon">{[24,48,72].map(h=><button type="button" key={h} aria-pressed={h===horizon} onClick={()=>{setHorizon(h);setSelected(0)}}>{h}h</button>)}</div></header><p>A higher line means more warning signs. It does not tell us for sure whether your flight will be late.</p>
    <div className="trip-risk-graphic"><small>Warning level: 0–100 · gray means we don’t know</small>
      <svg viewBox="0 0 720 190" preserveAspectRatio="none" role="img" aria-label="Heuristic operational pressure, zero to one hundred. Unknown points have no curve." onPointerMove={e=>{const rect=e.currentTarget.getBoundingClientRect();setSelected(Math.max(0,Math.min(rows.length-1,Math.round(((e.clientX-rect.left)/rect.width*720-30)/660*(rows.length-1)))));}}>
        {[0,50,100].map(s=><g key={s}><line x1="30" x2="690" y1={y(s)} y2={y(s)} stroke="#494952" strokeDasharray="3 5"/><text x="2" y={y(s)+4} fill="#c8c8d5" fontSize="12">{s}</text></g>)}
        {rows.map((row,i)=><g key={row.at}>{row.score===null?<rect x={x(i)-3} y="36" width="6" height="124" rx="3" fill="#656571" opacity=".35"/>:<><line x1={x(i)} x2={x(i)} y1="160" y2={y(row.score)} stroke={row.score>=60?'#ff827e':row.score>0?'#f3c47a':'#6fe1bb'} strokeWidth="9" opacity=".45"/>{i>0&&rows[i-1].score!==null&&<line x1={x(i-1)} y1={y(rows[i-1].score)} x2={x(i)} y2={y(row.score)} stroke="#c6b5ff" strokeWidth="3" vectorEffect="non-scaling-stroke"/>}<circle cx={x(i)} cy={y(row.score)} r={i===index?7:4} fill={row.score>=60?'#ff827e':row.score>0?'#f3c47a':'#6fe1bb'}/></>}</g>)}
      </svg><div className="timeline-axis"><span>Now</span><span>+{horizon/2} hours</span><span>+{horizon} hours</span></div></div>
    <label className="timeline-slider">Explore the timeline<input aria-label="Timeline time" type="range" min="0" max={rows.length-1} value={index} onChange={e=>setSelected(Number(e.target.value))}/></label>
    <div className={`timeline-evidence ${tone(r.score)}`}><div className="condition-reading" aria-live="polite"><span>{when(r.at)}</span><strong>{r.score===null?'Not enough information':r.score>=60?'More warning signs':r.score>0?'Some warning signs':'No problems found in the updates we have'}</strong>{r.score!==null&&<small>{r.score}/100 warning level · not a percentage chance</small>}</div><details><summary>What does this mean?</summary><p>{r.movement}</p>{r.facts.length?r.facts.map((f,i)=><div key={i}><b>{f.label}</b><p>{f.evidence}</p><small>{f.source} · fetched/observed {when(f.at)}</small></div>):<p>No applicable forecast or operational signal is available for this point.</p>}<small>Covered: {r.coverage.join(', ')||'none'}. Other factors remain unknown.</small></details></div>
    {connection&&<div className="connection-timeline"><strong>Your connection · {connection.onward}</strong><p>{connection.recommendation}</p><small>Departure {when(connection.departure_at)}. Connection is shown separately, not folded into a flight-delay probability.</small></div>}
    <details><summary>Where this information comes from</summary><p>{timeline.method}</p><p>{timeline.missing.join(' · ')}</p><small>Updated {when(timeline.updated_at)}. Drag the control to inspect each point.</small></details>
  </article>;
}

export function AirportPressureCard({data}){
  return <article className="airport-pressure"><span className="traveler-kicker">Airport conditions · some information may be missing</span><header><h4>{data.airport}</h4><strong className={tone(data.score)}>{data.score===null?'Unknown':`${data.score}/100`}</strong></header><p>{data.score===null?'We don’t have enough current information.':'This number summarizes reported weather and airport problems. It is not the chance your flight will be late.'}</p>{data.items.map((x,i)=><div className="pressure-factor" key={i}><strong>{x.label}</strong><p>{x.evidence}</p><small>{x.source} · {when(x.at)}</small></div>)}<details><summary>Sources &amp; limitations</summary><p>{data.method}</p><p>{data.missing.join(' · ')}</p><small>Checked {when(data.updated_at)}. A low supported score is not an all-clear.</small></details></article>;
}

export default function TripStrategy({data,url,query,onRefresh,connection}){
  const strategy=data.strategy,key=`disruption-backup:${url}?${query}`;
  const [prefs,setPrefs]=useState(()=>({...defaults,...read('disruption-preferences',{})})),[watch,setWatch]=useState(()=>read(key,{}).enabled===true),[state,setState]=useState(()=>{const v=read(key,{});return v.data?{data:v.data,saved:true}:{};}),[storageError,setStorageError]=useState(false);
  const generation=useRef(0);
  const prefsString=JSON.stringify(prefs);
  useEffect(()=>{const v=read(key,{});setWatch(v.enabled===true);setState(v.data?{data:v.data,saved:true}:{});generation.current++;return()=>{generation.current++;}},[key]);
  const savePrefs=value=>{setPrefs(value);setStorageError(!write('disruption-preferences',value));};
  useEffect(()=>{
    if(!watch)return;
    const controller=new AbortController(),current=++generation.current;
    setState(s=>({...s,loading:true,error:null}));
    fetch(`${url}/backups?${query}&${new URLSearchParams(Object.fromEntries(Object.entries(prefs).map(([k,v])=>[k,String(v)])))}`,{signal:controller.signal}).then(async r=>{const result=await r.json();if(!r.ok||result.status!=='available')throw Error(result.error||'Backup search is unavailable. Saved options are not a live availability check.');if(current===generation.current){setState({data:result});if(!write(key,{enabled:true,data:result}))setStorageError(true);}}).catch(e=>{if(e.name!=='AbortError'&&current===generation.current)setState(s=>({...s,loading:false,error:e.message,saved:!!s.data}));});
    return()=>{controller.abort();generation.current++;};
  },[watch,key,prefsString]);
  if(!strategy)return null;
  const toggle=()=>{const enabled=!watch;setWatch(enabled);if(!write(key,{enabled,data:state.data}))setStorageError(true);};
  const jump=(event,selector)=>{const target=event.currentTarget.closest('.trip-strategy').querySelector(selector);if(!target)return;if(target.tagName==='DETAILS')target.open=true;target.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});const focus=target.querySelector('summary,h4');if(focus){focus.tabIndex=-1;focus.focus({preventScroll:true});}};
  return <section className="trip-strategy" aria-label="Trip protection tools">
    <nav className="trip-shortcuts" aria-label="Find what you need"><button type="button" onClick={e=>jump(e,'.trip-timeline')}><span>01</span> What’s happening</button><button type="button" onClick={e=>jump(e,'.playbook-panel')}><span>02</span> What to do</button><button type="button" onClick={e=>jump(e,'.backup-watch')}><span>03</span> Backup flights</button></nav>
    <RiskTimeline timeline={strategy.timeline} connection={connection}/>
    <details className="playbook-panel"><summary>What should I do?</summary><p>Practical next steps, with the evidence behind each one. Original airline deadlines still apply.</p><div className="playbook-grid">{strategy.playbooks.map((p,i)=><article key={i}><span className="traveler-kicker">{p.classification}</span><h4>{p.title}</h4><dl>{[['Do this now',p.now],['Wait and watch',p.wait],['Call the airline if…',p.escalate],['Before you act',p.avoid]].map(([label,text])=><div key={label}><dt>{label}</dt><dd>{text}</dd></div>)}</dl><details><summary>Why we suggest this</summary><p>{p.evidence}</p><small>{p.source}</small></details></article>)}</div></details>
    <details className="airline-signal-panel"><summary>Behind the flight updates</summary><p>{strategy.airline_view.note}</p>{strategy.airline_view.signals.map((r,i)=><article key={i}><h4>{r.title}</h4><p>{r.detail}</p><small>{r.classification} · {r.source}</small></article>)}<p>{strategy.airline_view.unknown.join(' · ')}</p></details>
    <details><summary>Conditions at your two airports</summary><div className="playbook-grid">{strategy.airports.map((a,i)=><AirportPressureCard key={i} data={a}/>)}</div></details>
    <section className="backup-watch"><header><div><span className="traveler-kicker">Your plan B</span><h4>Backup flights</h4></div><button type="button" aria-pressed={watch} onClick={toggle}>{watch?'Pause updates':'Find backup flights'}</button></header><p>{watch?'Checking every five minutes while this page is open. Nothing is booked automatically.':'See alternative flights for your travel day and the next day. Nothing is booked automatically.'}</p><Preferences value={prefs} onChange={savePrefs}/>
      {storageError&&<p role="alert">Your browser could not save preferences or the watchlist. They may be lost when you leave.</p>}{state.loading&&<p role="status">Finding and cross-checking backup options…</p>}{state.error&&<p role="alert">{state.error}</p>}{state.saved&&<p className="saved-backup">These are saved results. Turn on updates to check again. Prices and available seats may have changed.</p>}
      {state.data&&<><p>{state.data.note}</p><small>Checked {when(state.data.checked_at)} · {watch?'Page-open watch enabled':'Watch paused'}</small><div className="backup-options">{state.data.flights?.map(f=><article key={f.key}><h4>{f.legs.map(l=>l.flight_number).join(' → ')}</h4><strong>{Number.isFinite(f.price_usd)?`Listed price: $${f.price_usd} USD`:'Price unavailable'}</strong><p>Depart {when(f.departure_at)}<br/>Arrive {when(f.arrival_at)}</p><p>{f.explanation}</p><p>{f.status_check.status==='matched'?`First flight: ${f.status_check.reported_status}`:'We haven’t confirmed the first flight’s status for this date.'}</p>{f.warnings.map(w=><p className="backup-caution" key={w}>{w}</p>)}<small>{f.missing.join(' · ')}</small><p>Ask the airline: “Can you move my booking to {f.legs.map(l=>l.flight_number).join(' and ')}? What would it cost?”</p></article>)}</div>{!state.data.flights?.length&&<p>{state.data.status==='unavailable'?'The provider could not return usable options.':'No returned option meets the time and preference checks.'} Ask the airline about rerouting; this is not proof that no flights exist.</p>}</>}
    </section>
  </section>;
}

export function AirportExplorer(){
  const [code,setCode]=useState(''),[state,setState]=useState({}),gen=useRef(0);
  useEffect(()=>()=>{gen.current++;},[]);
  async function check(e){e.preventDefault();const n=++gen.current;setState({loading:true});try{const r=await fetch(`${import.meta.env.BASE_URL}api/airports/${encodeURIComponent(code.trim().toUpperCase())}/pressure`);const d=await r.json();if(!r.ok)throw Error(d.error||'Airport information is unavailable.');if(n===gen.current)setState({data:d});}catch(e){if(n===gen.current)setState({error:e.message})}}
  return <section className="airport-explorer trip-strategy"><header><div><span className="traveler-kicker">Before you pick a flight</span><h2>How is the airport running?</h2></div></header><p>Check reported weather and airport problems. This does not show security lines or baggage waiting times.</p><form onSubmit={check}><label>Airport code (on your ticket)<input value={code} onChange={e=>{gen.current++;setState({});setCode(e.target.value)}} placeholder="e.g. JFK" maxLength={4} pattern="[A-Za-z]{3,4}" required/></label><button disabled={state.loading}>Check airport</button></form>{state.loading&&<p role="status">Checking airport conditions…</p>}{state.error&&<p role="alert">{state.error}</p>}{state.data&&<AirportPressureCard data={state.data}/>}</section>;
}
